beta1, beta2, beta = var('beta1 beta2 beta')
x, y, p = var('x y p')
Sigma = Matrix([[y,-p],[-p,x]])
obs = vector([beta1,beta2])
mea = vector([beta,beta])
quadform = (obs-mea)*Sigma*(obs-mea)
solve(quadform.diff(beta),beta)
f(beta1,beta2,x,y,p) = (-(beta1 + beta2)*p + beta2*x + beta1*y)/(-2*p + x + y)
f(0,1,0.4,10,1.7)
